//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KONUM
    {
        public int ID { get; set; }
        public string Konum { get; set; }
        public Nullable<int> personelID { get; set; }
    
        public virtual TBL_PERSON TBL_PERSON { get; set; }
    }
}
