//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSON()
        {
            this.TBL_ISLER = new HashSet<TBL_ISLER>();
            this.TBL_MESAJLAR = new HashSet<TBL_MESAJLAR>();
            this.TBL_KONUM = new HashSet<TBL_KONUM>();
        }
    
        public int ID { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelUsername { get; set; }
        public string personelPasswd { get; set; }
        public Nullable<int> personelBirimID { get; set; }
        public Nullable<int> personelYetkiID { get; set; }
        public bool personelAktiflik { get; set; }
    
        public virtual TBL_BIRIMLER TBL_BIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ISLER> TBL_ISLER { get; set; }
        public virtual TBL_YETKILER TBL_YETKILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MESAJLAR> TBL_MESAJLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KONUM> TBL_KONUM { get; set; }
    }
}
